# Generated by Django 3.1.5 on 2021-01-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.CharField(max_length=50)),
                ('image_category', models.CharField(choices=[('CA', 'Concept Art'), ('PD', 'Product Design')], default='CA', max_length=2)),
                ('image_field', models.ImageField(upload_to='gallery_images')),
                ('image_uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
