# Generated by Django 3.1.5 on 2021-01-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageunit',
            name='image_category',
            field=models.CharField(choices=[('CA', 'Concept Art'), ('PD', 'Product Design')], default='CA', max_length=2, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='imageunit',
            name='image_field',
            field=models.ImageField(upload_to='gallery_images', verbose_name='File Selection'),
        ),
        migrations.AlterField(
            model_name='imageunit',
            name='image_title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
    ]
